### ISSUE TITLE
Test and release for alternative node versions

### ISSUE THREAD

**Issue by antony** [antony/MAX7219.js#3]
Placeholder item for running and testing the library on:

- [x] Node < 10
- [x] Node > 10

I've replaced the pi-spi library, just waiting (about 10 hours so far) for node 12 to compile on my Raspberry Pi A so I can test it!

**Comment by lynniemagoo** [comment]
Antony,

When this is done, are you going to publish an update to NPM?   I'm currently pulling tarballs from my repository for my own use.  Would be great to get a published version.  I was wondering if you wanted to update the SPI to use spi-device or some other library as well?  I thought about doing that when I was working on the latest set of changes.

Thanks so much for your comments during the last pull request.  Greatly appreciated.   I have been doing software for 30 plus years and I eat my own dog food so to speak and know what it is like to have to support code that others have written. :-)

Sorry if this hijacks your thread. :-)   I have many things I would like to discuss with regard to this module.  Rather than write a novel here, I wondered if when you had time you'd reach out via email or facetime.  If you want to reach out privately, hit me @ my email address on yahoo.com  <myusername>@yahoo.com

Regards,
Lyndel

**Comment by antony** [comment]
Hi Lyndel,

>> When this is done, are you going to publish an update to NPM?

Absolutely! I've had the Pi compiling node for nearly a day now and it's still not done! Hopefully I'll be able to test this tomorrow AM and push the changes so that it can be released.

>>  was wondering if you wanted to update the SPI to use spi-device or some other library as well?

I won't have time to do this myself, but if you are so inclined, then I think this would be a great idea. I'm not 100% sure of the differences.

>> Thanks so much for your comments during the last pull request. 

My pleasure - I provide feedback as I would hope others would provide feedback to me, it's a great way to learn, and that's why we're all here - I think?

>> I have many things I would like to discuss with regard to this module

Happy to have a facetime sometime - I've got an insanely busy few months, but I'll try to grab some downtime and we can have a chat, I'd love for this module to get better and better, I love building things with displays.

In terms of where I want to go next, I'm thinking about getting one of the more modern full colour displays and building this:

https://tixy.land/
